export const users = {
    success: true,
    data: [
        {
            id: 1,
            username: "root",
            email: "amirenzevadev@gmail.com",
            status: "online",
        },
        {
            id: 2,
            username: "amir",
            email: "amirenzevadev@gmail.com",
            status: "offline",
        },
        {
            id: 3,
            username: "ali",
            email: "amirenzevadev@gmail.com",
            status: "online",
        },
        {
            id: 4,
            username: "Enzeva",
            email: "amirenzevadev@gmail.com",
            status: "you",
        },
    ],
};

export const messagesData = {
    data: [
        {
            id: 4,
            user1: 1,
            user2: 2,
            created_at: "2026-01-05T11:02:19.656858Z",
            messages: [
                {
                    id: 2,
                    chat: 4,
                    sender: "root",
                    message: "hi amit this is root",
                    created_at: "2026-01-05T12:26:31.378820Z",
                },
                {
                    id: 4,
                    chat: 4,
                    sender: "amir",
                    message: "hi root this is amir",
                    created_at: "2026-01-05T12:29:44.985472Z",
                },
                {
                    id: 5,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again",
                    created_at: "2026-01-05T14:02:30.920130Z",
                },
                {
                    id: 6,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again",
                    created_at: "2026-01-05T14:02:49.997950Z",
                },
                {
                    id: 7,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 8,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 9,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 10,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 11,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 12,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 13,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 14,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 15,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 16,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 17,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 18,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 19,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
                {
                    id: 20,
                    chat: 4,
                    sender: "root",
                    message: "hey this is root again and again and again",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
            ],
        },
        {
            id: 1,
            user1: 1,
            user2: 2,
            created_at: "2026-01-05T11:02:19.656858Z",
            messages: [
                {
                    id: 2,
                    chat: 4,
                    sender: "root",
                    message: "hi how are you ? ",
                    created_at: "2026-01-05T12:26:31.378820Z",
                },
                {
                    id: 4,
                    chat: 4,
                    sender: "amir",
                    message: "tnx 💓",
                    created_at: "2026-01-05T12:29:44.985472Z",
                },
                {
                    id: 5,
                    chat: 4,
                    sender: "root",
                    message: "im happy to hear that",
                    created_at: "2026-01-05T14:02:30.920130Z",
                },
                {
                    id: 6,
                    chat: 4,
                    sender: "root",
                    message: "i think i have feelings about you",
                    created_at: "2026-01-05T14:02:49.997950Z",
                },
                {
                    id: 7,
                    chat: 4,
                    sender: "root",
                    message: "i think i love you 😘",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
            ],
        },
        {
            id: 2,
            user1: 1,
            user2: 2,
            created_at: "2026-01-05T11:02:19.656858Z",
            messages: [
                {
                    id: 2,
                    chat: 4,
                    sender: "root",
                    message: "suuuuuuuuuuuuuuuuuu ",
                    created_at: "2026-01-05T12:26:31.378820Z",
                },
                {
                    id: 4,
                    chat: 4,
                    sender: "amir",
                    message: "whats going on men ? ",
                    created_at: "2026-01-05T12:29:44.985472Z",
                },
                {
                    id: 5,
                    chat: 4,
                    sender: "root",
                    message: "did your hear that ",
                    created_at: "2026-01-05T14:02:30.920130Z",
                },
                {
                    id: 6,
                    chat: 4,
                    sender: "root",
                    message: "CR7 is in africa",
                    created_at: "2026-01-05T14:02:49.997950Z",
                },
                {
                    id: 7,
                    chat: 4,
                    sender: "root",
                    message: "i cant belive that ",
                    created_at: "2026-01-05T15:50:39.833772Z",
                },
            ],
        },
    ],
};

export const chats = [
    {
        id: 1,
        users: [
            {
                id: 1,
                username: "root",
                email: "root@gmail.com",
                status: "online",
            },
            {
                id: 2,
                username: "amir",
                email: "amir@gmail.com",
                status: "offline",
            },
        ],
        created_at: "2026-01-05T11:02:19.656858Z",
        messages: [
            {
                id: 1,
                chat: 1,
                sender: "root",
                message: "hi amit its root",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 2,
                chat: 1,
                sender: "amir",
                message: "hi root its amir",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 3,
                chat: 1,
                sender: "root",
                message: "how are you amir ? ",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 4,
                chat: 1,
                sender: "amir",
                message: "im ok 👍. how about you ? ",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 5,
                chat: 1,
                sender: "root",
                message: "im fine too .",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 6,
                chat: 1,
                sender: "root",
                message: "thanks for asking",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
        ],
    },
    {
        id: 2,
        users: [
            {
                id: 1,
                username: "root",
                email: "root@gmail.com",
                status: "online",
            },
            {
                id: 3,
                username: "ali",
                email: "ali@gmail.com",
                status: "online",
            },
        ],
        created_at: "2026-01-05T11:02:19.656858Z",
        messages: [
            {
                id: 1,
                chat: 1,
                sender: "root",
                message: "hi amit its root",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 2,
                chat: 1,
                sender: "ali",
                message: "hi root its ali",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 3,
                chat: 1,
                sender: "root",
                message: "how are you ali ? ",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 4,
                chat: 1,
                sender: "ali",
                message: "im ok 👍. how about you ? ",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 5,
                chat: 1,
                sender: "root",
                message: "im fine too .",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
            {
                id: 6,
                chat: 1,
                sender: "root",
                message: "thanks for asking",
                created_at: "2026-01-05T12:26:31.378820Z",
            },
        ],
    },
];
